# Autogenerated wrapper script for ProtocolBuffers_jll for aarch64-apple-darwin
export libprotobuf

using CompilerSupportLibraries_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("ProtocolBuffers")
JLLWrappers.@declare_library_product(libprotobuf, "@rpath/libprotobuf.3.16.1.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libprotobuf,
        "lib/libprotobuf.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
