# Autogenerated wrapper script for ProtocolBuffers_jll for i686-w64-mingw32-cxx11
export libprotobuf

using CompilerSupportLibraries_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("ProtocolBuffers")
JLLWrappers.@declare_library_product(libprotobuf, "libprotobuf.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libprotobuf,
        "bin\\libprotobuf.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
